"""Writes the width steps of kit/styles/cs2uikit_votes.css (between the STEPS markers).

The server cannot send a width, only a class, so every bar is a set of steps: option bars in tenths (w0…w10),
the timer in twentieths (t0…t20).

Run: python kit/make_vote_steps.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CSS = os.path.join(HERE, "styles", "cs2uikit_votes.css")

rules = [f".vote-fill.w{i} {{ width: {i * 10}%; }}\n" for i in range(11)]
rules += [f".vote-timer-fill.t{i} {{ width: {i * 5}%; }}\n" for i in range(21)]
block = "/* STEPS:BEGIN — generated by kit/make_vote_steps.py, do not edit by hand */\n" + "".join(rules) + "/* STEPS:END */"
css = open(CSS, encoding="utf-8").read()
css = re.sub(r"/\* STEPS:BEGIN.*?/\* STEPS:END \*/", lambda _: block, css, flags=re.S)
open(CSS, "w", encoding="utf-8", newline="\n").write(css)
print("ok:", len(rules), "steps")
