"""Writes kit/layout/cs2uikit_toasts.xml: four toast cards, each with a pixel layer under its content.

A card is two layers on top of each other (the card itself does not flow):
  .toast-pixels — a calm field of small squares in the style colour, each breathing on its own cycle
                  (the same idea as PixelField on the website);
  .toast-row    — the icon and the text, flowing right.
The pixel layout is a fixed table, not random numbers, so every card and every rebuild look the same.

Run: python kit/make_toasts_layout.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "layout", "cs2uikit_toasts.xml")
CARDS = 4

# x, y in px inside the 460x104 card; size in px; cycle class (see .px-a … .px-d in the stylesheet).
# Denser on the right: the title on the left stays clean.
PIXELS = [
    (150, 14, 5, "a"), (196, 70, 4, "c"), (238, 30, 6, "b"), (270, 82, 5, "d"),
    (300, 12, 7, "c"), (322, 52, 4, "a"), (350, 24, 6, "d"), (366, 78, 8, "b"),
    (392, 44, 5, "c"), (410, 12, 6, "a"), (428, 66, 7, "d"), (444, 34, 4, "b"),
]


def card(i):
    # Position and size come from classes p0 … p11 written into the stylesheet below: an inline style="" attribute
    # made custom_hud_layout drop the whole layout, and no toast showed at all.
    px = "".join(f'<Panel class="toast-px px-{cyc} p{n}" hittest="false" />' for n, (x, y, s, cyc) in enumerate(PIXELS))
    return f'''				<Panel id="t{i}" class="toast" hittest="false">
					<Panel class="toast-pixels" hittest="false">{px}</Panel>
					<Panel class="toast-row" hittest="false">
						<Panel class="toast-halo" hittest="false">
							<Panel class="toast-dot" hittest="false"><Panel class="toast-glyph" hittest="false" /></Panel>
						</Panel>
						<Panel class="toast-body" hittest="false">
							<Label id="t{i}_title" class="toast-title" text="{{s:text}}" />
							<Label id="t{i}_msg" class="toast-msg" text="{{s:text}}" />
							<Label id="t{i}_link" class="toast-link" text="{{s:text}}" />
						</Panel>
					</Panel>
				</Panel>
'''


xml = f'''<!--
  CS2UIKit toasts: four cards per player, driven by CS2UIKit.Toasts. Generated by kit/make_toasts_layout.py.

  Rules of this file (see docs/GOTCHAS.md):
  - the root panel has no id (the resource compiler rejects it); the plugin toggles `toasts` inside it;
  - only Panel, Label, Image and Button are allowed in custom_hud_layout;
  - nothing here takes the mouse: hittest="false" everywhere, the panel never captures input.
-->
<root>
	<styles>
		<include src="s2r://panorama/styles/custom_game/cs2uikit_toasts.vcss_c" />
	</styles>

	<Panel class="cs2uikit-screen" hittest="false">
		<Panel id="toasts" class="toasts" hittest="false">
			<Panel class="toast-stack" hittest="false">

{"".join(card(i) for i in range(CARDS))}
			</Panel>
		</Panel>
	</Panel>
</root>
'''
open(OUT, "w", encoding="utf-8", newline="\n").write(xml)

# The pixel positions go into the stylesheet between the PIXELS markers.
CSS = os.path.join(HERE, "styles", "cs2uikit_toasts.css")
rules = "".join(
    f".toast-px.p{n} {{ width: {s}px; height: {s}px; margin-left: {x}px; margin-top: {y}px; }}\n"
    for n, (x, y, s, _) in enumerate(PIXELS)
)
block = "/* PIXELS:BEGIN — generated by kit/make_toasts_layout.py, do not edit by hand */\n" + rules + "/* PIXELS:END */"
css = open(CSS, encoding="utf-8").read()
if "PIXELS:BEGIN" in css:
    css = re.sub(r"/\* PIXELS:BEGIN.*?/\* PIXELS:END \*/", lambda _: block, css, flags=re.S)
else:
    css = css.replace(".px-a {", block + "\n\n.px-a {", 1)
open(CSS, "w", encoding="utf-8", newline="\n").write(css)
print("ok:", OUT)
