"""Writes kit/layout/cs2uikit_votes.xml: one vote card with up to five options.

The card is driven by CS2UIKit.Votes. Every text is a {s:text} dialog variable, every state a class:
  .on        — the card slides in from the left (the root stays shown, so the slide is a real transition);
  .used      — an option row that belongs to the current vote (rows past the option count stay collapsed);
  .mine      — the row the player voted for;
  .ended     — the vote is over: the timer goes, the winner row lights up (.winner), the card gets result-*.
Bars and the timer are width steps (w0…w10, t0…t20): the server cannot send a width, only a class.

Run: python kit/make_votes_layout.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "layout", "cs2uikit_votes.xml")
OPTIONS = 5


def option(i):
    return f'''					<Panel id="vote_opt_{i}" class="vote-opt" hittest="false">
						<Panel class="vote-opt-row" hittest="false">
							<Label id="vote_key_{i}" class="vote-key" text="{{s:text}}" />
							<Label id="vote_label_{i}" class="vote-label" text="{{s:text}}" />
							<Label id="vote_count_{i}" class="vote-count" text="{{s:text}}" />
						</Panel>
						<Panel class="vote-bar" hittest="false">
							<Panel id="vote_fill_{i}" class="vote-fill" hittest="false" />
						</Panel>
					</Panel>
'''


xml = f'''<!--
  CS2UIKit vote card, driven by CS2UIKit.Votes. Generated by kit/make_votes_layout.py.

  Rules of this file (see docs/GOTCHAS.md):
  - the root panel has no id (the resource compiler rejects it); the plugin toggles `votes` inside it;
  - only Panel, Label, Image and Button are allowed in custom_hud_layout, and no inline style="";
  - nothing here takes the mouse: votes are cast with !1…!5 in chat, the cursor stays in the game.
-->
<root>
	<styles>
		<include src="s2r://panorama/styles/custom_game/cs2uikit_votes.vcss_c" />
	</styles>

	<Panel class="cs2uikit-screen" hittest="false">
		<Panel id="votes" class="votes" hittest="false">
			<Panel id="vote_card" class="vote-card" hittest="false">
				<Panel class="vote-head" hittest="false">
					<Label id="vote_header" class="vote-header" text="{{s:text}}" />
					<Label id="vote_time" class="vote-time" text="{{s:text}}" />
				</Panel>
				<Label id="vote_question" class="vote-question" text="{{s:text}}" />
				<Panel class="vote-options" hittest="false">
{"".join(option(i) for i in range(OPTIONS))}				</Panel>
				<Panel class="vote-timer" hittest="false">
					<Panel id="vote_timer_fill" class="vote-timer-fill" hittest="false" />
				</Panel>
				<Label id="vote_hint" class="vote-hint" text="{{s:text}}" />
			</Panel>
		</Panel>
	</Panel>
</root>
'''
open(OUT, "w", encoding="utf-8", newline="\n").write(xml)
print("ok:", OUT)
