"""Writes the row rules of kit/styles/cs2uikit_toasts.css (between the ROWS markers).

Every card sits at the same spot; its place in the stack is only a transform. Moving a card up a row is then a
plain transform tween — no text moves between slots and nothing reflows, which Panorama cannot animate.
One rule per (row, state, direction) is tedious by hand, hence this script.

Run: python kit/make_toast_rows.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CSS = os.path.join(HERE, "styles", "cs2uikit_toasts.css")
ROWS = 4
STEP = 114          # card height 104 + gap 10
SLIDE = 28          # enter/leave slide distance

rules = []
for direction, sign, scope in (("down", 1, ""), ("up", -1, ".toasts.stack-up ")):
    for row in range(ROWS):
        y = sign * row * STEP
        rules.append(f"{scope}.toast.row-{row}\n{{\n\ttransform: translate3d( {SLIDE}px, {y}px, 0px );\n}}\n")
        rules.append(f"{scope}.toast.on.row-{row}\n{{\n\ttransform: translate3d( 0px, {y}px, 0px );\n}}\n")
        rules.append(f"{scope}.toast.on.leaving.row-{row}\n{{\n\ttransform: translate3d( {SLIDE}px, {y}px, 0px );\n}}\n")

block = "/* ROWS:BEGIN — generated by kit/make_toast_rows.py, do not edit by hand */\n\n" + "\n".join(rules) + "\n/* ROWS:END */"
css = open(CSS, encoding="utf-8").read()
css = re.sub(r"/\* ROWS:BEGIN.*?/\* ROWS:END \*/", lambda _: block, css, flags=re.S)
open(CSS, "w", encoding="utf-8", newline="\n").write(css)
print("ok:", len(rules), "rules")
